apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
  labels:
    app: todo-frontend
spec:
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      containers:
        - name: todo-frontend
          image: todo-frontend
          env:
            - name: VITE_API_URL
              value: "http://localhost:9191"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: frontend
              mountPath: /workdir
      volumes:
        - name: frontend
          hostPath:
            path: __REPO_PATH__/frontend/
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
spec:
  selector:
    app: todo-frontend
  type: ClusterIP
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
